version: 2

.build_template: &build_definition
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-pivo-flow-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "pivo_flow.gemspec" }}
          - v2-pivo-flow-bundle-{{ .Environment.CIRCLE_JOB }}-
    - run: bundle check || bundle install
    - save_cache:
        key: v2-pivo-flow-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "pivo_flow.gemspec" }}
        paths:
          - /usr/local/bundle
    - run: bundle exec rspec --require spec_helper --format documentation --color spec
  working_directory: ~/app

jobs:
  build:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3
  build_ruby2_2:
    <<: *build_definition
    docker:
      - image: ruby:2.2

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build
      - build_ruby2_4
      - build_ruby2_3
      - build_ruby2_2
